language: python
matrix:
  include:
    # Django 1.4: Python 2.6--2.7 (but Djrill doesn't support 2.6)
    - { env: DJANGO=django==1.4, python: 2.7 }
    # Django 1.5: Python 2.7, pypy
    - { env: DJANGO=django==1.5, python: 2.7 }
    - { env: DJANGO=django==1.5, python: pypy }
    # Django 1.6: Python 2.7--3.3, pypy
    - { env: DJANGO=django==1.6, python: 2.7 }
    - { env: DJANGO=django==1.6, python: 3.3 }
    - { env: DJANGO=django==1.6, python: pypy }
    # Django 1.7: Python 2.7--3.4, pypy
    - { env: DJANGO=django==1.7, python: 2.7 }
    - { env: DJANGO=django==1.7, python: 3.3 }
    - { env: DJANGO=django==1.7, python: 3.4 }
    - { env: DJANGO=django==1.7, python: pypy }
    # Django 1.8: "Python 2.7 or above"
    - { env: DJANGO=django==1.8, python: 2.7 }
    - { env: DJANGO=django==1.8, python: 3.4 }
    - { env: DJANGO=django==1.8, python: pypy }
    # Django 1.9 (prerelease): "Python 2.7, 3.4, or 3.5"
    - { env: DJANGO="--pre django", python: 2.7 }
    - { env: DJANGO="--pre django", python: 3.4 }
    - { env: DJANGO="--pre django", python: 3.5 }
    - { env: DJANGO="--pre django", python: pypy }
install:
  - pip install --upgrade setuptools pip
  - pip install -q $DJANGO
  - pip install .
  - pip list
script: python -Wall setup.py test
