sudo: false
language: python
matrix:
  include:
    # Django 1.8: "Python 2.7 or above"
    - { env: DJANGO=django==1.8, python: 2.7 }
    - { env: DJANGO=django==1.8, python: 3.4 }
    - { env: DJANGO=django==1.8, python: pypy }
    # Django 1.9: "Python 2.7, 3.4, or 3.5"
    - { env: DJANGO=django==1.9, python: 2.7 }
    - { env: DJANGO=django==1.9, python: 3.4 }
    - { env: DJANGO=django==1.9, python: 3.5 }
    - { env: DJANGO=django==1.9, python: pypy }
    # Django 1.10 (prerelease)
    - { env: DJANGO="--pre django", python: 2.7 }
    - { env: DJANGO="--pre django", python: 3.5 }
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade setuptools pip
  - pip install $DJANGO
  # For now, install all ESPs and test at once
  # (in future, might want to matrix ESPs to test cross-dependencies)
  - pip install .[mailgun,mandrill,postmark,sendgrid,sparkpost]
  - pip list
script: python setup.py test
